
services:
  redis_common:
    image: redis:latest
    container_name: redis_common
    restart: always
    # command: redis-server --port 6380
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis:/data
    environment:
      - REDIS_PORT=6379
      # - REDIS_DATABASES=2
    # networks:
      # - ecom_common
    network_mode: host

  rabbitmq_common:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_common
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: hoangpc
      RABBITMQ_DEFAULT_PASS: hoangpc
    # networks:
    #   - ecom_common
    network_mode: host

volumes:
  redis:
    driver: local

networks:
  ecom_common:
    external: true
