
services:
  postgres_client_api:
    image: postgres
    volumes:
      - postgres:/data/postgresql/db
    container_name: postgres_client_api
    restart: unless-stopped
    # environment:
    # - POSTGRES_HOST=localhost
    # - POSTGRES_PORT=5432
    # - POSTGRES_DB=client_api
    # - POSTGRES_USER=hoangpc
    # - POSTGRES_PASSWORD=hoangpc
    # - DATABASE_LOGGING=true
    env_file: 
      ../.env
    ports:
      - 5432:5432

  mongo_messaging:
    image: mongo:6-jammy
    volumes: 
      - mongodb:/data/mongodb/db
    ports: 
      - 27017:27017
    env_file: 
      ../.env
   
volumes:
  postgres:
    external: true
  mongodb: 
